server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habrdb
    driverClassName: org.postgresql.Driver
    username: "habrpguser"
    password: "pgpwd4habr"


  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/master.xml


